// <auto-generated />
using System;
using FiapGame.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiapGame.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417170206_ajustandoBiblioteca")]
    partial class ajustandoBiblioteca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiapGame.Domain.Biblioteca.Entities.BibliotecaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_atualizacao");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_cadastro");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("bibliotecas", (string)null);
                });

            modelBuilder.Entity("FiapGame.Domain.Biblioteca.Entities.ItemBibliotecaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibliotecaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_aquisicao");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_atualizacao");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_cadastro");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogo_id");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("BibliotecaId", "JogoId")
                        .IsUnique();

                    b.ToTable("itens_biblioteca", (string)null);
                });

            modelBuilder.Entity("FiapGame.Domain.Jogo.Entities.JogoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_atualizacao");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_cadastro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("jogos", (string)null);
                });

            modelBuilder.Entity("FiapGame.Domain.Usuario.Entities.UsuarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_atualizacao");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_cadastro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("FiapGame.Domain.Biblioteca.Entities.ItemBibliotecaEntity", b =>
                {
                    b.HasOne("FiapGame.Domain.Biblioteca.Entities.BibliotecaEntity", null)
                        .WithMany("Itens")
                        .HasForeignKey("BibliotecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiapGame.Domain.Jogo.Entities.JogoEntity", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("FiapGame.Domain.Usuario.Entities.UsuarioEntity", b =>
                {
                    b.OwnsOne("FiapGame.Domain.Usuario.ValuesObjects.EmailVo", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(150)")
                                .HasColumnName("email");

                            b1.HasKey("UsuarioEntityId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioEntityId");
                        });

                    b.OwnsOne("FiapGame.Domain.Usuario.ValuesObjects.SenhaVO", "Password", b1 =>
                        {
                            b1.Property<Guid>("UsuarioEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("varchar(255)")
                                .HasColumnName("password_hash");

                            b1.HasKey("UsuarioEntityId");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioEntityId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("FiapGame.Domain.Biblioteca.Entities.BibliotecaEntity", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
