// <auto-generated />
using System;
using FiapGame.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiapGame.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325180613_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiapGame.Domain.Usuario.Entities.UsuarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("FiapGame.Domain.Usuario.Entities.UsuarioEntity", b =>
                {
                    b.OwnsOne("FiapGame.Domain.Usuario.ValuesObjects.EmailVo", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(150)")
                                .HasColumnName("email");

                            b1.HasKey("UsuarioEntityId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioEntityId");
                        });

                    b.OwnsOne("FiapGame.Domain.Usuario.ValuesObjects.SenhaVO", "Password", b1 =>
                        {
                            b1.Property<Guid>("UsuarioEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("varchar(255)")
                                .HasColumnName("password_hash");

                            b1.HasKey("UsuarioEntityId");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioEntityId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
