// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FiapGame.BDD.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CriacaoDeUsuarioFeature : object, global::Xunit.IClassFixture<CriacaoDeUsuarioFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "Criação de Usuário", "  Como um visitante do sistema\r\n  Eu quero me cadastrar como usuário\r\n  Para que " +
                "eu possa acessar os recursos do sistema", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CriarUsuario.feature"
#line hidden
        
        public CriacaoDeUsuarioFeature(CriacaoDeUsuarioFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CriarUsuario.feature.ndjson", 6);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário com e-mail não registrado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criação de Usuário")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário com e-mail não registrado")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioComE_MailNaoRegistrado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário com e-mail não registrado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table1.AddRow(new string[] {
                            "Gabriel Teste",
                            "teste@fiapgame.com",
                            "Senha@123"});
#line 8
  await testRunner.GivenAsync("que eu informo os seguintes dados para cadastro:", ((string)(null)), table1, "Dado ");
#line hidden
#line 11
  await testRunner.AndAsync("o e-mail \"teste@fiapgame.com\" não está cadastrado no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
  await testRunner.WhenAsync("eu solicitar a criação do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 13
  await testRunner.ThenAsync("o usuário deve ser criado com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 14
  await testRunner.AndAsync("o repositório deve salvar as alterações", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário com e-mail já registrado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criação de Usuário")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário com e-mail já registrado")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioComE_MailJaRegistrado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário com e-mail já registrado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table2.AddRow(new string[] {
                            "Gabriel Teste",
                            "teste@fiapgame.com",
                            "Senha@123"});
#line 17
  await testRunner.GivenAsync("que eu informo os seguintes dados para cadastro:", ((string)(null)), table2, "Dado ");
#line hidden
#line 20
  await testRunner.AndAsync("o e-mail \"teste@fiapgame.com\" já está cadastrado no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 21
  await testRunner.WhenAsync("eu solicitar a criação do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 22
  await testRunner.ThenAsync("o sistema deve retornar um erro de domínio com a mensagem \"Email já cadastrado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário com e-mail inválido")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criação de Usuário")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário com e-mail inválido")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioComE_MailInvalido()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário com e-mail inválido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table3.AddRow(new string[] {
                            "Gabriel Teste",
                            "emailinvalido",
                            "Senha@123"});
#line 25
  await testRunner.GivenAsync("que eu informo os seguintes dados para cadastro:", ((string)(null)), table3, "Dado ");
#line hidden
#line 28
  await testRunner.WhenAsync("eu solicitar a criação do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 29
  await testRunner.ThenAsync("o sistema deve retornar um erro de domínio com a mensagem \"Email inválido\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cadastro de usuário com senha inválida")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criação de Usuário")]
        [global::Xunit.TraitAttribute("Description", "Cadastro de usuário com senha inválida")]
        public async global::System.Threading.Tasks.Task CadastroDeUsuarioComSenhaInvalida()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cadastro de usuário com senha inválida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha"});
                table4.AddRow(new string[] {
                            "Gabriel Teste",
                            "teste@fiapgame.com",
                            "fraca"});
#line 32
  await testRunner.GivenAsync("que eu informo os seguintes dados para cadastro:", ((string)(null)), table4, "Dado ");
#line hidden
#line 35
  await testRunner.WhenAsync("eu solicitar a criação do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 36
  await testRunner.ThenAsync("o sistema deve retornar um erro de domínio com a mensagem \"Senha deve ter no míni" +
                        "mo 8 caracteres com letras, números e especiais\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CriacaoDeUsuarioFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CriacaoDeUsuarioFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
